### PR TITLE
Update and add tests for Pytest

### PR DESCRIPTION
**Pull request by carlosmunozmoncayo**
I updated the tests from the remaining examples for compatibility with Pytest, trying to prioritize readability.
-  For most examples, I added .npy files with dictionaries containing expected solutions for regression tests. 
- Some tests still use some tools from pyclaw/util to also test the functionality of this module here.
- This PR contains only regression tests, accuracy is not checked yet.

### CODE REVIEW

**Comment by ketch** [comment]
Looking good.  I think at least one file is missing:

> E   FileNotFoundError: [Errno 2] No such file or directory: '/Users/ketch/Research/Software/clawpack/pyclaw/examples/burgers_1d/expected_sols.npy'

**Comment by ketch** [comment]
After removing that test, everything passes but I do get a few of these warnings:

```
pyclaw/examples/shallow_1d/test_shallow1d.py::TestShallowWater1D::test_dambreak
  /Users/ketch/Research/Software/clawpack/riemann/riemann/shallow_1D_py.py:128: RuntimeWarning: invalid value encountered in sqrt
    cbar = np.sqrt(0.5 * problem_data['grav'] * (q_l[0,:] + q_r[0,:]))
```
Not sure why.  Do you get the same @carlosmunozmoncayo ?

**Comment by carlosmunozmoncayo** [comment]
@ketch Yes, I am also getting those warnings. They come from the dam break simulation with the Python version of the HLL Riemann solver using Sharpclaw. It seems like the Riemann solver receives data with negative depth from the reconstruction at a single interface where the initial discontinuity is located. After that, the simulation runs successfully and gives a reasonable solution, which does not contain any negative depths or NaNs.

 I added the expected solutions for 1D Burgers.

**Comment by ketch** [comment]
This looks great.  I'll go ahead and squash the commits before merging, just to simplify the history a bit.

**Pull request merged**
